name: flutter_test_app
description: Flutter and Dart test.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  get: ^4.6.5
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^7.0.1
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env.dev
    - .env
